-- =============================================================================
-- 0850 — Profili normativi di sistema (FR-M3-01), generati da @aph/rai-engine SYSTEM_PROFILES.
-- Se il motore cambia i profili si aggiunge una NUOVA versione (BR-21), mai una modifica.
-- =============================================================================

with prof as (
  insert into app.regulation_profiles (scope, code, name, jurisdiction, is_template, is_default)
  values ('SYSTEM', 'IT-DM-1975', 'Nazionale — D.M. Sanità 5 luglio 1975', 'IT', false, true)
  returning id
)
insert into app.regulation_profile_versions (profile_id, version_number, parameters, legal_references, published_at)
select id, 1, '{"id":"IT-DM-1975","version":1,"name":"Nazionale — D.M. Sanità 5 luglio 1975","legalReferences":["D.M. Sanità 5 luglio 1975, artt. 1–7"],"checks":{"illuminating":true,"ventilating":true},"ratios":{"standard":{"illuminating":"0.125","ventilating":"0.125"},"attic":null,"atticRoofShareThreshold":"0.5"},"measurement":{"basis":"ARCHITECTURAL_OPENING","frameCoefficient":"1","exclusionHeightFromFloor":"0","overhang":{"method":"NONE","thresholdDepth":"0","factor":"0"},"roofOpeningCoefficient":"1"},"heights":{"habitable":"2.70","nonHabitable":"2.40","mountain":{"altitudeThreshold":1000,"habitable":"2.55"},"salvaCasaMinimum":"2.40"},"minimumAreas":{"singleBedroom":"9","doubleBedroom":"14","livingRoom":"14"},"studioApartment":{"onePerson":"28","twoPersons":"38","salvaCasaOnePerson":"20","salvaCasaTwoPersons":"28"},"perInhabitant":{"firstFour":"14","additional":"10"},"raiRequiredUses":["LIVING_ROOM","SINGLE_BEDROOM","DOUBLE_BEDROOM","KITCHEN","LIVING_WITH_KITCHENETTE","DINING","STUDY","STUDIO_ROOM","OTHER_HABITABLE"],"windowlessAllowedUses":["BATHROOM","WC","LAUNDRY","STORAGE","WALK_IN_CLOSET","HALLWAY","CORRIDOR","STAIRWELL","TECHNICAL","ATTIC_NON_HABITABLE","OTHER_ACCESSORY"],"ventilationRequiredUses":["BATHROOM","WC"],"allowedDerogations":[{"code":"D-99","label":"Altra deroga documentata dal progettista","legalReference":"","covers":["RAI_ILLUMINATING","RAI_VENTILATING","HEIGHT","MIN_AREA","VENTILATION","STUDIO_APARTMENT_AREA","OCCUPANCY_AREA"]}]}'::jsonb, array['D.M. Sanità 5 luglio 1975, artt. 1–7']::text[], now() from prof;

with prof as (
  insert into app.regulation_profiles (scope, code, name, jurisdiction, is_template, is_default)
  values ('SYSTEM', 'IT-DM-1975-SALVA-CASA', 'Nazionale — D.M. 1975 + Salva Casa (art. 24 c. 5-bis DPR 380/2001)', 'IT', false, false)
  returning id
)
insert into app.regulation_profile_versions (profile_id, version_number, parameters, legal_references, published_at)
select id, 1, '{"id":"IT-DM-1975-SALVA-CASA","version":1,"name":"Nazionale — D.M. 1975 + Salva Casa (art. 24 c. 5-bis DPR 380/2001)","legalReferences":["D.M. Sanità 5 luglio 1975, artt. 1–7","Art. 24, commi 5-bis e seguenti, D.P.R. 380/2001 (L. 105/2024)"],"checks":{"illuminating":true,"ventilating":true},"ratios":{"standard":{"illuminating":"0.125","ventilating":"0.125"},"attic":null,"atticRoofShareThreshold":"0.5"},"measurement":{"basis":"ARCHITECTURAL_OPENING","frameCoefficient":"1","exclusionHeightFromFloor":"0","overhang":{"method":"NONE","thresholdDepth":"0","factor":"0"},"roofOpeningCoefficient":"1"},"heights":{"habitable":"2.70","nonHabitable":"2.40","mountain":{"altitudeThreshold":1000,"habitable":"2.55"},"salvaCasaMinimum":"2.40"},"minimumAreas":{"singleBedroom":"9","doubleBedroom":"14","livingRoom":"14"},"studioApartment":{"onePerson":"28","twoPersons":"38","salvaCasaOnePerson":"20","salvaCasaTwoPersons":"28"},"perInhabitant":{"firstFour":"14","additional":"10"},"raiRequiredUses":["LIVING_ROOM","SINGLE_BEDROOM","DOUBLE_BEDROOM","KITCHEN","LIVING_WITH_KITCHENETTE","DINING","STUDY","STUDIO_ROOM","OTHER_HABITABLE"],"windowlessAllowedUses":["BATHROOM","WC","LAUNDRY","STORAGE","WALK_IN_CLOSET","HALLWAY","CORRIDOR","STAIRWELL","TECHNICAL","ATTIC_NON_HABITABLE","OTHER_ACCESSORY"],"ventilationRequiredUses":["BATHROOM","WC"],"allowedDerogations":[{"code":"D-01","label":"Salva Casa — art. 24 c. 5-bis DPR 380/2001 (L. 105/2024)","legalReference":"Art. 24, comma 5-bis, D.P.R. 380/2001 (D.L. 69/2024 conv. L. 105/2024)","covers":["HEIGHT","STUDIO_APARTMENT_AREA"]},{"code":"D-99","label":"Altra deroga documentata dal progettista","legalReference":"","covers":["RAI_ILLUMINATING","RAI_VENTILATING","HEIGHT","MIN_AREA","VENTILATION","STUDIO_APARTMENT_AREA","OCCUPANCY_AREA"]}]}'::jsonb, array['D.M. Sanità 5 luglio 1975, artt. 1–7', 'Art. 24, commi 5-bis e seguenti, D.P.R. 380/2001 (L. 105/2024)']::text[], now() from prof;

with prof as (
  insert into app.regulation_profiles (scope, code, name, jurisdiction, is_template, is_default)
  values ('SYSTEM', 'LOCAL-TEMPLATE', 'Modello "regolamento locale tipo" (da adattare e validare)', 'IT', true, false)
  returning id
)
insert into app.regulation_profile_versions (profile_id, version_number, parameters, legal_references, published_at)
select id, 1, '{"id":"LOCAL-TEMPLATE","version":1,"name":"Modello \"regolamento locale tipo\" (da adattare e validare)","legalReferences":["D.M. Sanità 5 luglio 1975, artt. 1–7","Regolamento edilizio comunale — articoli da indicare"],"checks":{"illuminating":true,"ventilating":true},"ratios":{"standard":{"illuminating":"0.125","ventilating":"0.125"},"attic":null,"atticRoofShareThreshold":"0.5"},"measurement":{"basis":"ARCHITECTURAL_OPENING","frameCoefficient":"1","exclusionHeightFromFloor":"0.60","overhang":{"method":"EXCLUDE_TOP_BAND","thresholdDepth":"1.20","factor":"0.5"},"roofOpeningCoefficient":"1"},"heights":{"habitable":"2.70","nonHabitable":"2.40","mountain":{"altitudeThreshold":1000,"habitable":"2.55"},"salvaCasaMinimum":"2.40"},"minimumAreas":{"singleBedroom":"9","doubleBedroom":"14","livingRoom":"14"},"studioApartment":{"onePerson":"28","twoPersons":"38","salvaCasaOnePerson":"20","salvaCasaTwoPersons":"28"},"perInhabitant":{"firstFour":"14","additional":"10"},"raiRequiredUses":["LIVING_ROOM","SINGLE_BEDROOM","DOUBLE_BEDROOM","KITCHEN","LIVING_WITH_KITCHENETTE","DINING","STUDY","STUDIO_ROOM","OTHER_HABITABLE"],"windowlessAllowedUses":["BATHROOM","WC","LAUNDRY","STORAGE","WALK_IN_CLOSET","HALLWAY","CORRIDOR","STAIRWELL","TECHNICAL","ATTIC_NON_HABITABLE","OTHER_ACCESSORY"],"ventilationRequiredUses":["BATHROOM","WC"],"allowedDerogations":[{"code":"D-02","label":"Deroga da regolamento locale (immobili vincolati / centro storico)","legalReference":"Regolamento edilizio comunale — articolo da indicare","covers":["RAI_ILLUMINATING","RAI_VENTILATING","HEIGHT"]},{"code":"D-03","label":"Ventilazione meccanica in sostituzione dell''aerazione naturale","legalReference":"Regolamento locale — articolo da indicare","covers":["RAI_VENTILATING"],"requiresMechanicalVentilation":true},{"code":"D-99","label":"Altra deroga documentata dal progettista","legalReference":"","covers":["RAI_ILLUMINATING","RAI_VENTILATING","HEIGHT","MIN_AREA","VENTILATION","STUDIO_APARTMENT_AREA","OCCUPANCY_AREA"]}],"isTemplate":true}'::jsonb, array['D.M. Sanità 5 luglio 1975, artt. 1–7', 'Regolamento edilizio comunale — articoli da indicare']::text[], now() from prof;

